spring:
  jackson.default-property-inclusion: NON_NULL
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  data:
    mongodb:
      host: 47.93.9.137
      port: 27017
      database: commonweal
  redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 10000
      pool:
        - max-idle: 8
        - min-idle: 0
        - max-active: 8
        - max-wait: -1
      password:
#  session:
#    store-type: redis
#    redis:
#      flush-mode:
#      namespace:
  cache:
    ehcache:
      config:
#  启用JAVAMAIL 请打开并设置下面的配置
#  mail:
#    host: smtp.qq.com
#    port: 587
#    username: 401569798@qq.com
#    password: cjrzzbkaulbkbhdh
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true

server:
  compression:
    enabled: true
  port: 8080
  session:
    timeout: 3600
  tomcat:
    uri-encoding: UTF-8
#server:
#    port: 8080
#    use-forward-headers: true
#    tomcat:
#      remote-ip-header: x-forwarded-for
#      protocol-header: x-forwarded-proto
#      port-header: X-Forwarded-Port
#      #其它设置是让Tomcat去Http头信息去获取协议信息，而不是从HttpServletRequest


hive:
  dev: true
  mongodb:
    host: ${spring.data.mongodb.host}
    port: ${spring.data.mongodb.port}
    database: ${spring.data.mongodb.database}
  exceptionsMap:
    101: "parameter invalid" #参数错误
    1011: "required parameter absent" #参数缺失
    1012: "未定义操作" #不可进行的操作
    1013: "parameter duplicate" #参数重复
    1014: "paramter format error" #参数格式不正确
    1015: "paramter expected value error" #期望参数值不正确
    102: "authorization error" #权限错误
    1021: "not login yet" #未登录报错
    1022: "modify other user's message" #修改他人信息
    1023: "group owner try to quit the acticity" #组长尝试退出活动
    103: "authentication error" #认证错误
    1031: "passport invalid" #用户不存在
    1032: "password incorrect" #密码错误
    1033: "email vertify error" #邮箱验证失败
    104: "resource unavailable" #资源不可用
    1041: "not found" #资源未找到
    1042: "user not found" #用户没有找到
    1043: "activity not found" #活动未找到
    1044: "application not found" #申请未找到
    1045: "activity member not found" #组员未找到
    1046: "none vertify token" #该邮箱没有验证码
    105: "duplicate object" #已有该数据对象
    1051: "user had already in the activity" #用户已经在该活动中了
    1061: "email server exception occur" #发送邮件出现了SERVEREXCEPTION错误
    1062: "email client exception occur" #发送邮件出现了CLIENTEXCEPTION错误
    201: "server unavailable" #服务器不可用，比如关机了/连不上什么的
    202: "server failure" #服务失败
    203: "service not ready" #服务暂未启用，比如后台还没写好
    204: "unknown server error" #服务器出现了奇怪的问题
    205: "encrypt error" #加密错误
    3001: "file system error" #文件系统错误


test:
  dev: false
  mongodb:
    host: 127.0.0.1
    port: ${spring.data.mongodb.port}
    database: "commonweal"
  exceptionsMap:
    101: "parameter invalid" #参数错误
    1011: "required parameter absent" #参数缺失
    1012: "未定义操作" #不可进行的操作
    1013: "parameter duplicate" #参数重复
    1014: "paramter format error" #参数格式不正确
    102: "authorization error" #权限错误
    1021: "not login yet" #未登录报错
    1022: "modify other user's message" #修改他人信息
    1023: "group owner try to quit the acticity" #组长尝试退出活动
    103: "authentication error" #认证错误
    1031: "passport invalid" #用户不存在
    1032: "password incorrect" #密码错误
    1033: "email vertify error" #邮箱验证失败
    104: "resource unavailable" #资源不可用
    1041: "not found" #资源未找到
    1042: "user not found" #用户没有找到
    1043: "activity not found" #活动未找到
    1044: "application not found" #申请未找到
    1045: "activity member not found" #组员未找到
    1046: "none vertify token" #该邮箱没有验证码
    1047: "college not found" #该大学信息没有找到
    105: "duplicate object" #已有该数据对象
    1061: "email server exception occur" #发送邮件出现了SERVEREXCEPTION错误
    1062: "email client exception occur" #发送邮件出现了CLIENTEXCEPTION错误
    201: "server unavailable" #服务器不可用，比如关机了/连不上什么的
    202: "server failure" #服务失败
    203: "service not ready" #服务暂未启用，比如后台还没写好
    204: "unknown server error" #服务器出现了奇怪的问题
    205: "encrypt error" #加密错误
    3001: "file system error" #文件系统错误